apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: app
  newName: stopudiv/app
  newTag: 552419886b6b19de82ee59cca67e5a6417bca04e
- name: hello-gitops
  newName: stopudiv/hello-gitops
  newTag: e64d5e5855aa17575c2ca11d8100679bdca20e68
