name: Blue/Green Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./app 
        file: ./app/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hello-gitops:upd, ${{ secrets.DOCKER_USERNAME }}/hello-gitops:latest
        platforms: linux/amd64,linux/arm64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache


    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK and install gke-gcloud-auth-plugin
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: '${{ secrets.GCP_PROJECT_ID }}'  # Optional: Set project ID if needed
    - run: |
        gcloud components install gke-gcloud-auth-plugin
        gcloud container clusters get-credentials "$GKE_CLUSTER" --region "$GKE_REGION"

    - name: Get the GKE credentials so we can deploy to the cluster
      run: |
        gcloud container clusters get-credentials "$GKE_CLUSTER" --region "$GKE_REGION"
    
    - name: Configure Docker for Google Container Registry
      run: |
        gcloud auth configure-docker

    - name: Build and push "blue" Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/app:blue .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/app:blue

    - name: Build and push "green" Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/app:green .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/app:green

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GCP_PROJECT }}

    - name: Deploy Blue
      run: |
        kubectl apply -f k8s/overlays/blue
        kubectl apply -f k8s/base

    - name: Deploy Green
      run: |
        kubectl apply -f k8s/overlays/green

    - name: Switch Traffic to Green
      run: |
        kubectl patch service app -p '{"spec":{"selector":{"app":"app","version":"green"}}}'
