# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        pytest

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./app 
        file: ./app/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }}, ${{ secrets.DOCKER_USERNAME }}/app:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache  
        
  deploy: 
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT }}
      GCP_CLUSTER: autopilot-cluster-1    # TODO: update to cluster name
      GCP_REGION: us-central1	   # TODO: update to cluster region

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.6.1"

    # Alternative option - authentication via credentials json
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK and install gke-gcloud-auth-plugin
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: '${{ secrets.GCP_PROJECT_ID }}'  # Optional: Set project ID if needed
    - run: |
        gcloud components install gke-gcloud-auth-plugin
        gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER}} --region ${{ secrets.GCP_REGION}} --project ${{ secrets.GCP_PROJECT}}

    - name: Get the GKE credentials so we can deploy to the cluster
      run: |
        gcloud container clusters get-credentials "$GCP_CLUSTER" --region "$GCP_REGION"

    - name: Create namespace & set in Kustomize
      run: |
         namespacePresentBlue=`kubectl get ns | grep python-app-blue | wc -l`
         namespacePresentGreen=`kubectl get ns | grep python-app-green | wc -l`
         if [ $namespacePresentBlue -eq 0 ]
         then
            kubectl create ns python-app-blue
            cd ./app/k8s
            kustomize edit set namespace python-app-blue
            echo "NEW_NAMESPACE=python-app-blue" >> $GITHUB_ENV
            echo "OLD_NAMESPACE=python-app-green" >> $GITHUB_ENV
         elif [ $namespacePresentGreen -eq 0 ]
         then
            kubectl create ns python-app-green
            cd ./app/k8s
            kustomize edit set namespace python-app-green
            echo "NEW_NAMESPACE=python-app-green" >> $GITHUB_ENV
            echo "OLD_NAMESPACE=python-app-blue" >> $GITHUB_ENV
         else
            echo "Both Blue and Green namespaces are present. Establishing the active namespace"
            PODS_IN_BLUE=$(kubectl get pods -n python-app-blue -l app=app --no-headers 2>/dev/null | wc -l)
            PODS_IN_GREEN=$(kubectl get pods -n python-app-green -l app=app --no-headers 2>/dev/null | wc -l)
            if [ "$PODS_IN_BLUE" -gt 0 ]; then
              echo "The active namespace is $NAMESPACE_BLUE"
              echo "OLD_NAMESPACE=python-app-blue" >> $GITHUB_ENV
              echo "NEW_NAMESPACE=python-app-green" >> $GITHUB_ENV
            elif [ "$PODS_IN_GREEN" -gt 0 ]; then
              echo "The active namespace is $NAMESPACE_GREEN"
              echo "OLD_NAMESPACE=python-app-green" >> $GITHUB_ENV
              echo "NEW_NAMESPACE=python-app-blue" >> $GITHUB_ENV
            else
              echo "No active namespace found!"
            fi
         fi

    - name: Update Kubernetes resources
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
       cd ./app/k8s
       kustomize edit set image app=$DOCKER_USERNAME/app:$GITHUB_SHA
       cat kustomization.yaml
    
    - name: Deploy updated Kubernetes resources
      run: |
        kubectl apply -k ./app/k8s/ 

    - name: Switch traffic to the new namespace
      run: |
        #Get current version
        currentVersion=$(kubectl get service app -n app -o=jsonpath='{.spec.selector.version}')
        
        # Update the patch version
        newVersion=$(echo $currentVersion | awk -F. '{$NF = $NF + 1; print $1"."$2"."$3}' | tr -d '[:space:]')
        
        # Patch the service with the new version
        echo "Updating service to use version $newVersion..."
        kubectl patch service app -n app -p "{\"spec\":{\"selector\":{\"version\":\"$newVersion\"}}}"


    - name: Remove old namespace
      run: |
        namespacePresentOld=`kubectl get ns | grep ${{ env.OLD_NAMESPACE }} | wc -l`
        if [ $namespacePresentOld -eq 1 ]
        then
          kubectl delete ns ${{ env.OLD_NAMESPACE }} --wait=true
        fi


    - name: Update service.yaml with the new version
      run: |
        echo "Fetching currently new version from service selector..."
        newVersion=$(kubectl get service app -n app -o=jsonpath='{.spec.selector.version}')
        echo "Updating service.yaml with version $newVersion..."
        sed -i "s/version: .*/version: $newVersion/" app/k8s/service.yaml
        echo "Updated service.yaml:"
        cat github-actions-samples/k8s/service.yaml
 
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Bump docker tag"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} 
    
